Sprint 7 increment 17
gopherlearning/track-devops pull request #34
Opened 2022-08-01 14:31 UTC by gopherlearning

2022-08-03 20:06 UTC, Bazys requested changes
2 основные причины из-за которых прошу переделать:
1. сместь табличных тестов и функциональных в одном методе (и достаточно часто.
2. не всегда корректная работа с контекстом.
В том же [Testify](https://github.com/stretchr/testify) посмотри на работу с  пакетом `suite` помжет разделить логику, так как ты захочешь

2022-08-03 20:06 UTC, Bazys commented on internal/metrics/store_test.go
> +func Example() {
по моему немного надуманный пример.
Может потом подумаешь и сам решишь, какая функция в твоем проекте самая сложная и к ней напишешь пример?

2022-08-03 20:06 UTC, Bazys commented on cmd/server/main.go
>  	DatabaseDSN   string        `short:"d" help:"трока с адресом подключения к БД" env:"DATABASE_DSN"`
```suggestion
	DatabaseDSN   string        `short:"d" help:"строка с адресом подключения к БД" env:"DATABASE_DSN"`
```

2022-08-03 20:06 UTC, Bazys commented on cmd/server/main.go
>  			logrus.Error(err)
в будующих инкриментах научись работать с чем то посоверменне логруса, типа зеролог или зап.
лигрус по сути своей сотался синхронным и недалеко ушел от стандартного логера.

2022-08-03 20:06 UTC, Bazys commented on cmd/server/main.go
> +			ticker := time.NewTicker(5 * time.Second)
вынеси 5 хотя бы в константу.
А в продакшн системах такие вещи выносят в настройки.

2022-08-03 20:06 UTC, Bazys commented on internal/metrics/metrics.go
> +	ErrTooSHortKey      = errors.New("слошком короткий ключ")
я правильно понимаю, что по сути эти переменные нужны тольк для проверок в тестах, в основном коде нигде не сравнивается эта ошибка?

2022-08-03 20:06 UTC, Bazys commented on internal/metrics/types_test.go
> +	m := NewStore([]byte("secret"))
зачем разные тесты в одной тестовой функции?
я бы не смешивал табличные тесты с функциональными.

2022-08-03 20:06 UTC, Bazys commented on internal/server/storage/postgres/storage.go
> +		_, err = tx.Exec(context.Background(), `INSERT INTO metrics (target,id, hash, mtype, mdelta, mvalue) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING`, target, n.ID, n.Hash, n.MType, n.Delta,
у тебя в функцию передется контектс, а ты тут начинаешь использовать context.Background() ?
да и массовую вставку лучше делать через подготовленное выражение

2022-08-03 20:06 UTC, Bazys commented on internal/server/storage/postgres/storage.go
> +func (s *Storage) Metrics(target string) (map[string][]metrics.Metrics, error) {
где то есть контекст, а где то нет?

2022-08-03 20:06 UTC, Bazys commented on internal/server/web/echo_test.go
> +				require.NoError(t, s.UpdateMetric(context.Background(), tt.target, metrics.Metrics{MType: m[2], ID: m[3], Delta: metrics.GetInt64Pointer(tt.value["counter"].(int64)), Value: metrics.GetFloat64Poi
в тестах я предпочитаю использвать context.TODO() - суть одна, но понятно что разработчик осознает что это не совсем корректное применение

2022-08-09 07:30 UTC, gopherlearning commented on internal/metrics/metrics.go
> +	ErrTooSHortKey      = errors.New("слошком короткий ключ")
Синтетически задал, что если ключ короче определённого значения, то выдать ошибку

2022-08-15 06:40 UTC, gopherlearning commented on internal/metrics/types_test.go
> +	m := NewStore([]byte("secret"))
#93407a6da232a56a6e92e71f342ae8083dd3c9e1

2022-08-15 09:07 UTC, gopherlearning commented on internal/server/storage/postgres/storage.go
> +		_, err = tx.Exec(context.Background(), `INSERT INTO metrics (target,id, hash, mtype, mdelta, mvalue) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING`, target, n.ID, n.Hash, n.MType, n.Delta,
Исправил. Не сразу понял как использовать Prepare в **pgx**, но провалился в код и нашёл там мапку с подготовленными запросами.
https://github.com/gopherlearning/track-devops/pull/34/commits/40ffccbddf0e05e88ce97db4f09407448152f1d7

2022-08-15 09:35 UTC, gopherlearning commented on internal/server/web/echo_test.go
> +				require.NoError(t, s.UpdateMetric(context.Background(), tt.target, metrics.Metrics{MType: m[2], ID: m[3], Delta: metrics.GetInt64Pointer(tt.value["counter"].(int64)), Value: metrics.GetFloat64Poi
Исправил https://github.com/gopherlearning/track-devops/pull/34/commits/97de711e06f810b821eff4e028fa64e079842930

2022-08-15 09:35 UTC, gopherlearning commented on internal/server/storage/postgres/storage.go
> +func (s *Storage) Metrics(target string) (map[string][]metrics.Metrics, error) {
Исправил https://github.com/gopherlearning/track-devops/pull/34/commits/97de711e06f810b821eff4e028fa64e079842930

2022-08-15 09:40 UTC, gopherlearning commented on cmd/server/main.go
> +			ticker := time.NewTicker(5 * time.Second)
Исправил https://github.com/gopherlearning/track-devops/pull/34/commits/31422ff9064188f6892739fd29ca3c3a3c3a839f

2022-08-15 09:41 UTC, gopherlearning commented on cmd/server/main.go
>  			logrus.Error(err)
Посмотрел на zerolog, очень понравился, добавлю в следующих инкрементах

2022-08-15 09:42 UTC, gopherlearning commented on internal/metrics/store_test.go
> +func Example() {
В следующих инкрементах хочу добавить мок тесты на postgres storage, и там же добавить пример. На данный момент сделал лёгкий вариант удовлетворить требованию задания.

2022-08-15 10:35 UTC, Bazys approved these changes

2022-08-15 11:51 UTC, merged